### PR TITLE
New items

### PR DESCRIPTION
**Pull request by opattison**
- Core competency
- Customer success

### CODE REVIEW

**Comment by RoelN** [comment]
Thanks! Could you take a look at why it's throwing a conflict?

**Comment by opattison** [comment]
Hmm – just fixed the merge conflict on my end (by catching up to your master) and GitHub still thinks it is a problem. I'll give it a second look, but if it isn't a quick fix on your end or mine, feel free to close it up.

**Comment by RoelN** [comment]
Thanks. I don't know what's going on here, but I'll try to have a look tonight. I'd rather solve this than just close it :)

**Comment by opattison** [comment]
Just fixed whitespace and GitHub still isn’t pleased. Moving forward, I don’t know how to close the loop on this low hanging fruit.

**Comment by RoelN** [comment]
@opattison Still, thanks for the effort! Sorry I'm not too active with this anymore (the project was more to figure out how fonts worked, not to maintain a buzzword list ;)

**Comment by opattison** [comment]
No problem! Just cleaning up my GitHub a bit. Great work on this font.

**Pull request closed without merging**
